/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Odev;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean isBetween(ArrayList<Integer> array, Integer min, Integer max) {
        System.out.println("inside search");
        if (array == null) return false;
        if (array.isEmpty())return false;
        for (int elt : array) {
          if (elt < min || elt > max) return false;
        }
        return true;
      }
}
